/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.thedivineengine.init;

import net.neoforged.neoforge.registries.DeferredRegister;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredHolder;
import net.neoforged.neoforge.capabilities.RegisterCapabilitiesEvent;
import net.neoforged.neoforge.capabilities.Capabilities;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.bus.api.SubscribeEvent;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.BlockItem;

import net.mcreator.thedivineengine.item.inventory.Backpacktier2InventoryCapability;
import net.mcreator.thedivineengine.item.inventory.BackpackInventoryCapability;
import net.mcreator.thedivineengine.item.*;
import net.mcreator.thedivineengine.TheDivineEngineMod;

@EventBusSubscriber
public class TheDivineEngineModItems {
	public static final DeferredRegister.Items REGISTRY = DeferredRegister.createItems(TheDivineEngineMod.MODID);
	public static final DeferredItem<Item> INDUSTRIALFURNANCE;
	public static final DeferredItem<Item> STEEL_INGOT;
	public static final DeferredItem<Item> STEEL_PICKAXE;
	public static final DeferredItem<Item> STEELBLOCK;
	public static final DeferredItem<Item> STEELAXE;
	public static final DeferredItem<Item> THEDIVINEENGINEICON;
	public static final DeferredItem<Item> STEELSWORD;
	public static final DeferredItem<Item> STEELSHOVEL;
	public static final DeferredItem<Item> STEELHOE;
	public static final DeferredItem<Item> IRONHAMMER;
	public static final DeferredItem<Item> IRONPLATE;
	public static final DeferredItem<Item> STEELPLATE;
	public static final DeferredItem<Item> STEELPLATEBLOCK;
	public static final DeferredItem<Item> IRONPLATEBLOCK;
	public static final DeferredItem<Item> CRUSHER;
	public static final DeferredItem<Item> IRONDUST;
	public static final DeferredItem<Item> GOLDDUST;
	public static final DeferredItem<Item> COPPERDUST;
	public static final DeferredItem<Item> COPPERWIRE;
	public static final DeferredItem<Item> SILICONWAFER;
	public static final DeferredItem<Item> COPPERPLATE;
	public static final DeferredItem<Item> CHIP;
	public static final DeferredItem<Item> BACKPACK;
	public static final DeferredItem<Item> DIAMONDCRUSHERWHEELS;
	public static final DeferredItem<Item> MECHANICALPARTS;
	public static final DeferredItem<Item> STEELWIPE;
	public static final DeferredItem<Item> STEELGEARS;
	public static final DeferredItem<Item> INSULATEDCOPPERWIRE;
	public static final DeferredItem<Item> ALUMINIUMORE;
	public static final DeferredItem<Item> ALUMINIUMRAWORE;
	public static final DeferredItem<Item> ALUMINIUMINGOT;
	public static final DeferredItem<Item> ALUMINIUMDUST;
	public static final DeferredItem<Item> ELECTRUMDUST;
	public static final DeferredItem<Item> ELECTRUMINGOT;
	public static final DeferredItem<Item> COPPERPICKAXE;
	public static final DeferredItem<Item> COPPERAXE;
	public static final DeferredItem<Item> COPPERSWORD;
	public static final DeferredItem<Item> COPPERSHOVEL;
	public static final DeferredItem<Item> COPPERHOE;
	public static final DeferredItem<Item> THE_DIVINE_ENGINE_ITEM;
	public static final DeferredItem<Item> STEEL_ARMOR_HELMET;
	public static final DeferredItem<Item> STEEL_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> STEEL_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> STEEL_ARMOR_BOOTS;
	public static final DeferredItem<Item> ALUMINIUMBLOCK;
	public static final DeferredItem<Item> ALUMINIUMPLATE;
	public static final DeferredItem<Item> COPPERARMOR_HELMET;
	public static final DeferredItem<Item> COPPERARMOR_CHESTPLATE;
	public static final DeferredItem<Item> COPPERARMOR_LEGGINGS;
	public static final DeferredItem<Item> COPPERARMOR_BOOTS;
	public static final DeferredItem<Item> ALUMINIUMPLATEBLOCK;
	public static final DeferredItem<Item> ELECTRUMPLATE;
	public static final DeferredItem<Item> ELECTRUMWIRE;
	public static final DeferredItem<Item> INSULATED_ELECTRUM_WIRE;
	public static final DeferredItem<Item> INSULATINGTAPE;
	public static final DeferredItem<Item> PLANTSHREDDER;
	public static final DeferredItem<Item> PLANTFIBER;
	public static final DeferredItem<Item> SHREDDERBLADES;
	public static final DeferredItem<Item> SILICON;
	public static final DeferredItem<Item> COPPERCOIL;
	public static final DeferredItem<Item> ROTOR;
	public static final DeferredItem<Item> MAGNETITEORE;
	public static final DeferredItem<Item> MAGNETITERAWORE;
	public static final DeferredItem<Item> PROCESSEDMAGNETITE;
	public static final DeferredItem<Item> MOTOR;
	public static final DeferredItem<Item> ELCTRIC_GENERATOR;
	public static final DeferredItem<Item> WHEEL_FOR_HAND_DYNAMO;
	public static final DeferredItem<Item> TITANIUMORE;
	public static final DeferredItem<Item> TITANIUMRAWORE;
	public static final DeferredItem<Item> TITANIUMINGOT;
	public static final DeferredItem<Item> TITAMIUMPLATE;
	public static final DeferredItem<Item> STEELHAMMER;
	public static final DeferredItem<Item> TITANIUMBLOCK;
	public static final DeferredItem<Item> THEBASISOFAMECHANICALMACHINE;
	public static final DeferredItem<Item> BACKPACKTIER_2;
	public static final DeferredItem<Item> BASISTIER_2;
	public static final DeferredItem<Item> HEMP;
	public static final DeferredItem<Item> HARVESTEDHEMP;
	public static final DeferredItem<Item> COPPER_WIRE_BLOCK;
	public static final DeferredItem<Item> COPPER_WIRE_BLOCK_13452;
	public static final DeferredItem<Item> ANCIENT_BASIS;
	public static final DeferredItem<Item> ANCIENT_RECIPE;
	public static final DeferredItem<Item> PIECE_OF_QN_QNCIENT_RECIPE;
	public static final DeferredItem<Item> ALUMINIUM_PICKAXE;
	public static final DeferredItem<Item> ALUMINIUMAXE;
	public static final DeferredItem<Item> ALUMINIUM_SHOVEL;
	public static final DeferredItem<Item> ALUMINIUM_HOE;
	public static final DeferredItem<Item> ALUMINIUM_SWORD;
	public static final DeferredItem<Item> ALUMINIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> ALUMINIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> ALUMINIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> ALUMINIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> TITANIUM_PICKAXE;
	public static final DeferredItem<Item> TITANIUM_AXE;
	public static final DeferredItem<Item> TITANIUM_SHOVEL;
	public static final DeferredItem<Item> TITANIUM_HOE;
	public static final DeferredItem<Item> TITANIUM_SWORD;
	public static final DeferredItem<Item> TITANIUM_ARMOR_HELMET;
	public static final DeferredItem<Item> TITANIUM_ARMOR_CHESTPLATE;
	public static final DeferredItem<Item> TITANIUM_ARMOR_LEGGINGS;
	public static final DeferredItem<Item> TITANIUM_ARMOR_BOOTS;
	public static final DeferredItem<Item> REMAINS_OF_THE_ANCIENTS;
	public static final DeferredItem<Item> CUTTING_BOARD;
	public static final DeferredItem<Item> TABLE;
	public static final DeferredItem<Item> SHEETANDINK;
	public static final DeferredItem<Item> CHAIR;
	public static final DeferredItem<Item> FURNITURE_CRAFTING_TABLE;
	static {
		INDUSTRIALFURNANCE = block(TheDivineEngineModBlocks.INDUSTRIALFURNANCE);
		STEEL_INGOT = REGISTRY.register("steel_ingot", SteelIngotItem::new);
		STEEL_PICKAXE = REGISTRY.register("steel_pickaxe", SteelPickaxeItem::new);
		STEELBLOCK = block(TheDivineEngineModBlocks.STEELBLOCK);
		STEELAXE = REGISTRY.register("steelaxe", SteelaxeItem::new);
		THEDIVINEENGINEICON = REGISTRY.register("thedivineengineicon", ThedivineengineiconItem::new);
		STEELSWORD = REGISTRY.register("steelsword", SteelswordItem::new);
		STEELSHOVEL = REGISTRY.register("steelshovel", SteelshovelItem::new);
		STEELHOE = REGISTRY.register("steelhoe", SteelhoeItem::new);
		IRONHAMMER = REGISTRY.register("ironhammer", IronhammerItem::new);
		IRONPLATE = REGISTRY.register("ironplate", IronplateItem::new);
		STEELPLATE = REGISTRY.register("steelplate", SteelplateItem::new);
		STEELPLATEBLOCK = block(TheDivineEngineModBlocks.STEELPLATEBLOCK);
		IRONPLATEBLOCK = block(TheDivineEngineModBlocks.IRONPLATEBLOCK);
		CRUSHER = block(TheDivineEngineModBlocks.CRUSHER);
		IRONDUST = REGISTRY.register("irondust", IrondustItem::new);
		GOLDDUST = REGISTRY.register("golddust", GolddustItem::new);
		COPPERDUST = REGISTRY.register("copperdust", CopperdustItem::new);
		COPPERWIRE = REGISTRY.register("copperwire", CopperwireItem::new);
		SILICONWAFER = REGISTRY.register("siliconwafer", SiliconwaferItem::new);
		COPPERPLATE = REGISTRY.register("copperplate", CopperplateItem::new);
		CHIP = REGISTRY.register("chip", ChipItem::new);
		BACKPACK = REGISTRY.register("backpack", BackpackItem::new);
		DIAMONDCRUSHERWHEELS = REGISTRY.register("diamondcrusherwheels", DiamondcrusherwheelsItem::new);
		MECHANICALPARTS = REGISTRY.register("mechanicalparts", MechanicalpartsItem::new);
		STEELWIPE = REGISTRY.register("steelwipe", SteelwipeItem::new);
		STEELGEARS = REGISTRY.register("steelgears", SteelgearsItem::new);
		INSULATEDCOPPERWIRE = REGISTRY.register("insulatedcopperwire", InsulatedcopperwireItem::new);
		ALUMINIUMORE = block(TheDivineEngineModBlocks.ALUMINIUMORE);
		ALUMINIUMRAWORE = REGISTRY.register("aluminiumrawore", AluminiumraworeItem::new);
		ALUMINIUMINGOT = REGISTRY.register("aluminiumingot", AluminiumingotItem::new);
		ALUMINIUMDUST = REGISTRY.register("aluminiumdust", AluminiumdustItem::new);
		ELECTRUMDUST = REGISTRY.register("electrumdust", ElectrumdustItem::new);
		ELECTRUMINGOT = REGISTRY.register("electrumingot", ElectrumingotItem::new);
		COPPERPICKAXE = REGISTRY.register("copperpickaxe", CopperpickaxeItem::new);
		COPPERAXE = REGISTRY.register("copperaxe", CopperaxeItem::new);
		COPPERSWORD = REGISTRY.register("coppersword", CopperswordItem::new);
		COPPERSHOVEL = REGISTRY.register("coppershovel", CoppershovelItem::new);
		COPPERHOE = REGISTRY.register("copperhoe", CopperhoeItem::new);
		THE_DIVINE_ENGINE_ITEM = REGISTRY.register("the_divine_engine_item", TheDivineEngineItemItem::new);
		STEEL_ARMOR_HELMET = REGISTRY.register("steel_armor_helmet", SteelArmorItem.Helmet::new);
		STEEL_ARMOR_CHESTPLATE = REGISTRY.register("steel_armor_chestplate", SteelArmorItem.Chestplate::new);
		STEEL_ARMOR_LEGGINGS = REGISTRY.register("steel_armor_leggings", SteelArmorItem.Leggings::new);
		STEEL_ARMOR_BOOTS = REGISTRY.register("steel_armor_boots", SteelArmorItem.Boots::new);
		ALUMINIUMBLOCK = block(TheDivineEngineModBlocks.ALUMINIUMBLOCK);
		ALUMINIUMPLATE = REGISTRY.register("aluminiumplate", AluminiumplateItem::new);
		COPPERARMOR_HELMET = REGISTRY.register("copperarmor_helmet", CopperarmorItem.Helmet::new);
		COPPERARMOR_CHESTPLATE = REGISTRY.register("copperarmor_chestplate", CopperarmorItem.Chestplate::new);
		COPPERARMOR_LEGGINGS = REGISTRY.register("copperarmor_leggings", CopperarmorItem.Leggings::new);
		COPPERARMOR_BOOTS = REGISTRY.register("copperarmor_boots", CopperarmorItem.Boots::new);
		ALUMINIUMPLATEBLOCK = block(TheDivineEngineModBlocks.ALUMINIUMPLATEBLOCK);
		ELECTRUMPLATE = REGISTRY.register("electrumplate", ElectrumplateItem::new);
		ELECTRUMWIRE = REGISTRY.register("electrumwire", ElectrumwireItem::new);
		INSULATED_ELECTRUM_WIRE = REGISTRY.register("insulated_electrum_wire", InsulatedElectrumWireItem::new);
		INSULATINGTAPE = REGISTRY.register("insulatingtape", InsulatingtapeItem::new);
		PLANTSHREDDER = block(TheDivineEngineModBlocks.PLANTSHREDDER);
		PLANTFIBER = REGISTRY.register("plantfiber", PlantfiberItem::new);
		SHREDDERBLADES = REGISTRY.register("shredderblades", ShredderbladesItem::new);
		SILICON = REGISTRY.register("silicon", SiliconItem::new);
		COPPERCOIL = REGISTRY.register("coppercoil", CoppercoilItem::new);
		ROTOR = REGISTRY.register("rotor", RotorItem::new);
		MAGNETITEORE = block(TheDivineEngineModBlocks.MAGNETITEORE);
		MAGNETITERAWORE = REGISTRY.register("magnetiterawore", MagnetiteraworeItem::new);
		PROCESSEDMAGNETITE = REGISTRY.register("processedmagnetite", ProcessedmagnetiteItem::new);
		MOTOR = REGISTRY.register("motor", MotorItem::new);
		ELCTRIC_GENERATOR = block(TheDivineEngineModBlocks.ELCTRIC_GENERATOR);
		WHEEL_FOR_HAND_DYNAMO = REGISTRY.register("wheel_for_hand_dynamo", WheelForHandDynamoItem::new);
		TITANIUMORE = block(TheDivineEngineModBlocks.TITANIUMORE);
		TITANIUMRAWORE = REGISTRY.register("titaniumrawore", TitaniumraworeItem::new);
		TITANIUMINGOT = REGISTRY.register("titaniumingot", TitaniumingotItem::new);
		TITAMIUMPLATE = REGISTRY.register("titamiumplate", TitamiumplateItem::new);
		STEELHAMMER = REGISTRY.register("steelhammer", SteelhammerItem::new);
		TITANIUMBLOCK = block(TheDivineEngineModBlocks.TITANIUMBLOCK);
		THEBASISOFAMECHANICALMACHINE = block(TheDivineEngineModBlocks.THEBASISOFAMECHANICALMACHINE, new Item.Properties().stacksTo(16));
		BACKPACKTIER_2 = REGISTRY.register("backpacktier_2", Backpacktier2Item::new);
		BASISTIER_2 = block(TheDivineEngineModBlocks.BASISTIER_2, new Item.Properties().stacksTo(16));
		HEMP = block(TheDivineEngineModBlocks.HEMP);
		HARVESTEDHEMP = REGISTRY.register("harvestedhemp", HarvestedhempItem::new);
		COPPER_WIRE_BLOCK = block(TheDivineEngineModBlocks.COPPER_WIRE_BLOCK);
		COPPER_WIRE_BLOCK_13452 = block(TheDivineEngineModBlocks.COPPER_WIRE_BLOCK_13452);
		ANCIENT_BASIS = block(TheDivineEngineModBlocks.ANCIENT_BASIS, new Item.Properties().stacksTo(1).rarity(Rarity.UNCOMMON));
		ANCIENT_RECIPE = REGISTRY.register("ancient_recipe", AncientRecipeItem::new);
		PIECE_OF_QN_QNCIENT_RECIPE = REGISTRY.register("piece_of_qn_qncient_recipe", PieceOfQnQncientRecipeItem::new);
		ALUMINIUM_PICKAXE = REGISTRY.register("aluminium_pickaxe", AluminiumPickaxeItem::new);
		ALUMINIUMAXE = REGISTRY.register("aluminiumaxe", AluminiumaxeItem::new);
		ALUMINIUM_SHOVEL = REGISTRY.register("aluminium_shovel", AluminiumShovelItem::new);
		ALUMINIUM_HOE = REGISTRY.register("aluminium_hoe", AluminiumHoeItem::new);
		ALUMINIUM_SWORD = REGISTRY.register("aluminium_sword", AluminiumSwordItem::new);
		ALUMINIUM_ARMOR_HELMET = REGISTRY.register("aluminium_armor_helmet", AluminiumArmorItem.Helmet::new);
		ALUMINIUM_ARMOR_CHESTPLATE = REGISTRY.register("aluminium_armor_chestplate", AluminiumArmorItem.Chestplate::new);
		ALUMINIUM_ARMOR_LEGGINGS = REGISTRY.register("aluminium_armor_leggings", AluminiumArmorItem.Leggings::new);
		ALUMINIUM_ARMOR_BOOTS = REGISTRY.register("aluminium_armor_boots", AluminiumArmorItem.Boots::new);
		TITANIUM_PICKAXE = REGISTRY.register("titanium_pickaxe", TitaniumPickaxeItem::new);
		TITANIUM_AXE = REGISTRY.register("titanium_axe", TitaniumAxeItem::new);
		TITANIUM_SHOVEL = REGISTRY.register("titanium_shovel", TitaniumShovelItem::new);
		TITANIUM_HOE = REGISTRY.register("titanium_hoe", TitaniumHoeItem::new);
		TITANIUM_SWORD = REGISTRY.register("titanium_sword", TitaniumSwordItem::new);
		TITANIUM_ARMOR_HELMET = REGISTRY.register("titanium_armor_helmet", TitaniumArmorItem.Helmet::new);
		TITANIUM_ARMOR_CHESTPLATE = REGISTRY.register("titanium_armor_chestplate", TitaniumArmorItem.Chestplate::new);
		TITANIUM_ARMOR_LEGGINGS = REGISTRY.register("titanium_armor_leggings", TitaniumArmorItem.Leggings::new);
		TITANIUM_ARMOR_BOOTS = REGISTRY.register("titanium_armor_boots", TitaniumArmorItem.Boots::new);
		REMAINS_OF_THE_ANCIENTS = block(TheDivineEngineModBlocks.REMAINS_OF_THE_ANCIENTS);
		CUTTING_BOARD = block(TheDivineEngineModBlocks.CUTTING_BOARD);
		TABLE = block(TheDivineEngineModBlocks.TABLE);
		SHEETANDINK = block(TheDivineEngineModBlocks.SHEETANDINK);
		CHAIR = block(TheDivineEngineModBlocks.CHAIR);
		FURNITURE_CRAFTING_TABLE = block(TheDivineEngineModBlocks.FURNITURE_CRAFTING_TABLE);
	}

	// Start of user code block custom items
	// End of user code block custom items
	@SubscribeEvent
	public static void registerCapabilities(RegisterCapabilitiesEvent event) {
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new BackpackInventoryCapability(stack), BACKPACK.get());
		event.registerItem(Capabilities.ItemHandler.ITEM, (stack, context) -> new Backpacktier2InventoryCapability(stack), BACKPACKTIER_2.get());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block) {
		return block(block, new Item.Properties());
	}

	private static DeferredItem<Item> block(DeferredHolder<Block, Block> block, Item.Properties properties) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), properties));
	}
}